import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

def main(xml_file):
    # Initialize the GTK Builder
    builder = Gtk.Builder()

    try:
        # Load the XML file generated by Glade
        builder.add_from_file(xml_file)
    except Exception as e:
        print(f"Error loading XML file: {e}")
        return

    # Get the main window from the XML file
    window = builder.get_object("main_window")  # Replace "main_window" with the actual ID of your main window in Glade
    if not window:
        print("Main window not found in the XML file.")
        return

    # Connect signals defined in Glade to the methods in this script
    builder.connect_signals({
        "on_destroy": Gtk.main_quit,  # Handles window close
    })

    # Show the window
    window.show_all()

    # Start the GTK main loop
    Gtk.main()

if __name__ == "__main__":
    xml_file = "./teste.glade"
    main(xml_file)
